version: '3.8'
services:
  db:
    image: postgres:14
    container_name: myapp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myapp
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: myapp-web
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data: